[package]
name = "screen-cut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
winit = "0.28.3"
log = "0.4.17"
pretty_env_logger = "0.4.0"